# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
    README\.md|
    notramp/resources/|
    notramp/test/|
    notramp/test_self/|
    \.git/|
    \.github/
  )

default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch # prevents commit to main/master branch

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
      # - id: black-jupyter

  # prettier for JSON, CSS, HTML, Markdown, YAML, JavaScript, TypeScript
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier

  # # sorts (alphabetically) and groups (thematically) import statements
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.30.0
  #   hooks:
  #     - id: markdownlint-fix
  #       args: [-c, .markdownlint.yaml]
# # sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
# ci:
#   autoupdate_schedule: weekly
#   skip: []
#   submodules: false
