# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test_NoTramp

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest # ubuntu-20.04 

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install conda   
      uses: conda-incubator/setup-miniconda@v2
      with: 
          # auto-update-conda: true
          python-version: "3.10"
          auto-activate-base: true

    - name: Install dependencies
      shell: bash -el {0}
      run: |
          conda activate
          python -m pip install --upgrade pip
          pip install psutil
          conda install -c bioconda minimap2
    
    - name: Run NoTramp all mode with single amplicons as reads
      shell: bash -el {0}
      run: |
         pwd
         conda activate
         conda list
         python notramp/notramp_main.py -a -p /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/ARTIC_SARS-CoV-2_v5.3.2_400.primer.bed -r /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/ARTIC_v5.3.2_Amplicons_Wuhan1_reference.fasta -g /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/MN908947.3_SARS-CoV2_Wuhan-reference.fasta
         echo "Showing contents of logfile:"
         cat /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/notramp.log
         rm /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/notramp.log
    
    - name: Run NoTramp all mode with empty reads-file 
      shell: bash -el {0}
      run: |
         pwd
         conda activate
         conda list
         python notramp/notramp_main.py -a -p /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/ARTIC_SARS-CoV-2_v5.3.2_400.primer.bed -r /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/empty_reads_file.fasta -g /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/MN908947.3_SARS-CoV2_Wuhan-reference.fasta
         echo "Showing contents of logfile:"
         cat /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/notramp.log
    
    - name: Run NoTramp trimming mode only 
      shell: bash -el {0}
      run: |
         pwd
         conda activate
         conda list
         python notramp/notramp_main.py -t -p /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/ARTIC_SARS-CoV-2_v5.3.2_400.primer.bed -r /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/ARTIC_v5.3.2_Amplicons_Wuhan1_reference.fasta -g /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/MN908947.3_SARS-CoV2_Wuhan-reference.fasta
         echo "Showing contents of logfile:"
         cat /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/notramp.log
         rm /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/notramp.log
  
    - name: Run NoTramp coverage capping mode only 
      shell: bash -el {0}
      run: |
         pwd
         conda activate
         conda list
         python notramp/notramp_main.py -c -p /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/ARTIC_SARS-CoV-2_v5.3.2_400.primer.bed -r /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/ARTIC_v5.3.2_Amplicons_Wuhan1_reference.fasta -g /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/MN908947.3_SARS-CoV2_Wuhan-reference.fasta
         echo "Showing contents of logfile:"
         cat /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/notramp.log
         rm /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/notramp.log

   # - name: Install dependencies
   #   run: |
   #     python -m pip install --upgrade pip
   #     pip install flake8 pytest
   #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   # - name: Lint with flake8
   #   run: |
   #     # stop the build if there are Python syntax errors or undefined names
   #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
   #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
   #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
   # - name: Test with pytest
   #   run: |
   #     pytest
