# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test_NoTramp

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "created" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.10", "3.x"]
    # steps:
    #   - uses: actions/setup-python@v5
    #     with:
    #       python-version: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        # python-version: "3.10"
        # python-version: "3.x"
        python-version: ${{ matrix.python-version }}

    - name: Install conda   
      uses: conda-incubator/setup-miniconda@v3
      with: 
          # auto-update-conda: true
          # channels: bioconda, conda-forge
          # channel-priority: strict
          # activate-environment: env_name
          miniforge-version: latest
          # python-version: "3.10"
          # python-version: 3.*
          python-version: ${{ matrix.python-version == '3.x' && '3.*' || matrix.python-version }}
          auto-activate-base: true
          conda-remove-defaults: true
          use-mamba: true

    - name: Install required and recommended dependencies
      shell: bash -el {0}
      run: |
          conda activate
          python -m pip install --upgrade pip
          pip install psutil
          conda install -c bioconda minimap2
    
    - name: Run NoTramp all mode with single amplicons as reads
      shell: bash -el {0}
      run: |
         pwd
         conda activate
         conda list
         python notramp/notramp_main.py -a -p /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/ARTIC_SARS-CoV-2_v5.3.2_400.primer.bed -r /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/ARTIC_v5.3.2_Amplicons_Wuhan1_reference.fasta -g /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/MN908947.3_SARS-CoV2_Wuhan-reference.fasta
         echo "Showing contents of logfile:"
         cat /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/notramp.log
         rm /home/runner/work/NoTrAmp/NoTrAmp/notramp/test/notramp.log